# Music Genre Classifier

### Description
[Description of project goes here]

## 1 - Import Libraries and Dataset

In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

# Load the dataset
data_3s = pd.read_csv('../dataset/features_3_sec.csv') # Dataset for the 3 second featureset
data_30s = pd.read_csv('../dataset/features_30_sec.csv') # Dataset for the 30 second featureset

data = data_3s # Just change this instead of changing every single variable

first_20_rows = data.head(20)
first_20_rows

filename  length  chroma_stft_mean  chroma_stft_var  rms_mean  \
0   blues.00000.0.wav   66149          0.335406         0.091048  0.130405   
1   blues.00000.1.wav   66149          0.343065         0.086147  0.112699   
2   blues.00000.2.wav   66149          0.346815         0.092243  0.132003   
3   blues.00000.3.wav   66149          0.363639         0.086856  0.132565   
4   blues.00000.4.wav   66149          0.335579         0.088129  0.143289   
5   blues.00000.5.wav   66149          0.376670         0.089702  0.132618   
6   blues.00000.6.wav   66149          0.379909         0.088827  0.130335   
7   blues.00000.7.wav   66149          0.331880         0.092119  0.140600   
8   blues.00000.8.wav   66149          0.347877         0.094209  0.133130   
9   blues.00000.9.wav   66149          0.358061         0.082957  0.115312   
10  blues.00001.0.wav   66149          0.402401         0.090340  0.093024   
11  blues.00001.1.wav   66149          0.345507         0.091037  0.094656   
12  blues.00001.2.wav   66149          0.338119         0.083682  0.097776   
13  blues.00001.3.wav   66149          0.330751         0.093936  0.085365   
14  blues.00001.4.wav   66149          0.348027         0.100096  0.088437   
15  blues.00001.5.wav   66149          0.329435         0.104149  0.093201   
16  blues.00001.6.wav   66149          0.343666         0.096098  0.089783   
17  blues.00001.7.wav   66149          0.327732         0.099648  0.110633   
18  blues.00001.8.wav   66149          0.329428         0.090254  0.111013   
19  blues.00001.9.wav   66149          0.292987         0.082145  0.094924   

     rms_var  spectral_centroid_mean  spectral_centroid_var  \
0   0.003521             1773.065032          167541.630869   
1   0.001450             1816.693777           90525.690866   
2   0.004620             1788.539719          111407.437613   
3   0.002448             1655.289045          111952.284517   
4   0.001701             1630.656199           79667.267654   
5   0.003583             1994.915219          211700.619569   
6   0.003166             1962.150096          177443.070045   
7   0.002546             1701.890924           35678.130616   
8   0.002538             1746.473502          138073.931244   
9   0.001846             1763.948942           61493.423121   
10  0.003876             1279.182242          406513.816744   
11  0.001495             1513.763969          214768.804443   
12  0.001386             1308.869728          154209.122448   
13  0.002641             1479.530348          646868.373151   
14  0.002204             1729.640428          568827.519152   
15  0.001929             1492.089309          228951.553214   
16  0.002173             1571.420445          257630.094708   
17  0.003306             1877.638297          510311.370648   
18  0.001072             1665.600276          239973.571541   
19  0.003031             1373.437553          210606.446462   

    spectral_bandwidth_mean  spectral_bandwidth_var  ...  mfcc16_var  \
0               1972.744388           117335.771563  ...   39.687145   
1               2010.051501            65671.875673  ...   64.748276   
2               2084.565132            75124.921716  ...   67.336563   
3               1960.039988            82913.639269  ...   47.739452   
4               1948.503884            60204.020268  ...   30.336359   
5               2152.767854            74263.873102  ...   31.448069   
6               2146.503479            98020.541422  ...   33.954071   
7               1979.387612            36670.725886  ...   38.456211   
8               1887.619723           117069.920049  ...   44.311455   
9               1874.195710            51944.921435  ...   43.967834   
10              1921.306192           196573.441648  ...   39.640743   
11              2091.432928           121877.017611  ...   58.940536   
12              1508.008806           111306.051891  ...   63.200188   
13              1906.454247           3577

## 2 - Preprocess the Data

In [32]:
# Rid the dataset of useless rows
data = data.drop('filename', axis=1)

# Separate features and target
X = data.drop('label', axis=1)
y = data['label']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the features (maybe we need this or maybe not, TODO maybe test the results without this)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## 3 - Train a machine learning model

### 3.1 - Random Forest Classifier

In [33]:
# Initialize and train the classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

### 3.2 - Keras Neural Network

In [34]:
# Encode genre names to integers
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

# Convert labels to one-hot encoding
y_train_onehot = to_categorical(y_train_encoded)
y_test_onehot = to_categorical(y_test_encoded)

# Creating the Keras Neural Network
model = Sequential()
# Adding Layers (like an onion)
# Using Rectified Linear Unit (ReLU)
# TODO test using Exponential Linear Units (ELUs) or add another variable to compare it to or something
model.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax')) # Softmax for output in probabilities

# Finialising the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(X_train, y_train_onehot, validation_data=(X_test, y_test_onehot), epochs=100, batch_size=32, verbose=1)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 1.2717 - accuracy: 0.5648 - val_loss: 0.9145 - val_accuracy: 0.6917
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7934 - accuracy: 0.7326 - val_loss: 0.7470 - val_accuracy: 0.7513
Epoch 3/100
250/250 [==============================] - 0s 992us/step - loss: 0.6435 - accuracy: 0.7869 - val_loss: 0.6597 - val_accuracy: 0.7718
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5425 - accuracy: 0.8211 - val_loss: 0.6188 - val_accuracy: 0.7868
Epoch 5/100
250/250 [==============================] - 0s 996us/step - loss: 0.4773 - accuracy: 0.8410 - val_loss: 0.5695 - val_accuracy: 0.8073
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4209 - accuracy: 0.8607 - val_loss: 0.5246 - val_accuracy: 0.8303
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3704 - accuracy: 0.8806 - val_loss: 0.4941 - val_accuracy: 0.

Visually mapping the old labels with their integer variations

In [35]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)

# Print the mapping of genre names to integers
genre_mapping = dict(zip(encoder.classes_, range(len(encoder.classes_))))
print(genre_mapping)

{'blues': 0, 'classical': 1, 'country': 2, 'disco': 3, 'hiphop': 4, 'jazz': 5, 'metal': 6, 'pop': 7, 'reggae': 8, 'rock': 9}


## 4 - Evaluating the Models

In [48]:
# RandomForest Classifier
y_pred = clf.predict(X_test)
print("RandomForest Classifier Report:")
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

# Keras Neural Network
# Get the genre names from the encoder
genre_names = encoder.classes_

y_pred_onehot = model.predict(X_test)
y_pred_labels = np.argmax(y_pred_onehot, axis=1)
y_pred_genres = encoder.inverse_transform(y_pred_labels)

print("\nKeras Neural Network Report:")
print(classification_report(y_test, y_pred_genres, target_names=genre_names))
print(confusion_matrix(y_test_encoded, y_pred_labels))

# # Keras Neural Network
# y_pred_onehot = model.predict(X_test)
# y_pred_labels = np.argmax(y_pred_onehot, axis=1)
# print("\nKeras Neural Network Report:")
# print(classification_report(y_test_encoded, y_pred_labels))
# print(confusion_matrix(y_test_encoded, y_pred_labels))

RandomForest Classifier Report:
              precision    recall  f1-score   support

       blues       0.87      0.87      0.87       208
   classical       0.94      0.98      0.96       203
     country       0.80      0.84      0.82       186
       disco       0.85      0.83      0.84       199
      hiphop       0.92      0.89      0.90       218
        jazz       0.86      0.93      0.89       192
       metal       0.87      0.95      0.91       204
         pop       0.92      0.95      0.93       180
      reggae       0.92      0.88      0.90       211
        rock       0.89      0.72      0.79       197

    accuracy                           0.88      1998
   macro avg       0.88      0.88      0.88      1998
weighted avg       0.88      0.88      0.88      1998

[[180   1   8   4   2   6   3   0   3   1]
 [  0 199   0   0   0   4   0   0   0   0]
 [ 13   0 156   4   0   8   2   2   1   0]
 [  1   1   3 166   8   2   3   2   6   7]
 [  4   0   4   2 193   1   8   4   1

## 5 - Comparing the Model Performance

[add some waffle here about that or something]
[Make sure to change this as we add new models to compare to]

##### 5.1 - Accuracy
This is the ratio of the number of correct predictions to the total number of predictions. In this case, the RandomForest Classifier has an accuracy of 88%, while the Keras Neural Network has an accuracy of 87%. Both models perform relatively well, with RandomForest having a slightly higher accuracy.

#### 5.2 - Precision
This is the ratio of true positive predictions to the sum of true positive and false positive predictions. It measures how well the model correctly identifies positive samples. For both models, you can see that the precision values for each genre vary. Overall, RandomForest and Keras perform similarly in terms of precision.

#### 5.3 - Recall
This is the ratio of true positive predictions to the sum of true positive and false negative predictions. It measures the ability of the model to find all the positive samples. Similar to precision, recall values also vary for each genre, and both models have comparable recall scores.

#### 5.4 - F1-score
The F1-score is the harmonic mean of precision and recall. It balances both precision and recall, providing a single metric for comparison. For most genres, the F1-scores are close between the RandomForest and Keras models.

#### 5.5 - Summary
Generally you can see that accross all the numerical metrics the Keras Neural Net performed slightly better

You can see however that there are notable differences between the performances in each genre

In [ ]:
# TODO Maybe even add some code too idk figure it out

## 6 - Make predictions
Here we choose the better model to make the predictions and actually do some predictions